#cloud-config
package_update: true
package_upgrade: true

packages:
  - httpd

runcmd:
  - systemctl start httpd
  - systemctl enable httpd
  - echo "<h1>Deployed via Terraform & Cloud-Init</h1>" > /var/www/html/index.html